language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 5.4
#    - env: DBTYPE=mysql; MW=1.25.0
#      php: 5.4
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_script: bash ./build/travis/before_script.sh

script: bash ./build/travis/script.sh

after_success: bash ./build/travis/after_success.sh